### ISSUE TITLE
Wrong codelist showing for V2.01 and V2.02 for Organisation Type

### ISSUE THREAD

**Issue by anjesh** [IATI/IATI-Websites#197]
Looks like http://iatistandard.org/201/codelists/OrganisationType/ and http://iatistandard.org/202/codelists/OrganisationType/  are showing codelist of V2.03. 

![image](https://user-images.githubusercontent.com/120488/42258110-da340c48-7f79-11e8-97e1-4e3f34c8ad1d.png)

https://github.com/IATI/IATI-Codelists-NonEmbedded/commit/096857a6dbffb196bbd700385c7b05bfde7cf0c6#diff-5ee7a365afc039a009c9e8ec5034e01e shows V2.03 types being added.

**Comment by andylolz** [comment]
Hi @anjesh!

So, since OrganisationType is now a non-embedded codelist, the list of possible codes should now be the same for all versions (non-embedded codelists are deployed from `master` for all IATI versions, whereas embedded codelists are deployed from version branches corresponding to IATI versions).

So it’s now correct that OrganisationType should appear the same for v2.0x and indeed for v1.0x.

I’m not sure whether that covers what you’re asking. Does it?

**Comment by samuele-mattiuzzo** [comment]
@amy-silcock @PetyaKangalova do you know if this is still relevant or can be closed?

**Comment by amy-silcock** [comment]
@andylolz is correct here.  I will close the issue. @anjesh do get in contact with us if you have further questions.
